import "../globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import styles from "./auth.module.css";

export const metadata = {
  title: "Authentication",
  description: "Generated by create next app",
};

export default function AuthLayout({ children }) {
  return (
    <main style={{background:"#f1f1f1"}}>
    {children}
    </main>
  );
}
